name: Lint Tests

on:
  push:

jobs:
  test:
    name: test App
    runs-on: ubuntu-22.04

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '19'
        - run: npm install
        - run: npm run lint

#  build:
#    name: Build image
#    # Faire le job pour build l'image docker
#
#  test:
#    name: App test
#    # Faire le job pour curl l'app