name: Lint

on:
  push:

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-22.04

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '19'
        - run: |
                npm install
                npm run lint

        - uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile
