name: Lint Tests

on:
  push:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install
        run: npm install

      - name: Run Lint
        run: npm run lint