name: Build Docker Image and Make Curl Request

on:
  push:
    branches: [main]  # Déclencher le workflow sur les push vers la branche main
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build-and-curl:
    name: Build Docker Image and Make Curl Request
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - run: docker build -t myimage -f Dockerfile .
      - run: docker container run --name mycontainer -p 3000:3000 myimage
      - run: sleep 10
      - run: curl -s -w "%{http_code}" 127.0.0.1:3000
      - run:
          if [ $? -ne 200 ]; then
            echo "La requête curl a échoué avec un code de réponse différent de 200."
            exit 1
          fi