name: Test Docker image / api

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build-and-curl:
    name: Test Docker image and run of api
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - run: |
              docker build -t myimage -f Dockerfile .
              docker container run --name mycontainer -d -p 3000:3000 myimage
              sleep 5

      - run: |
              response=$(curl -s -w "%{http_code}" 127.0.0.1:3000)
              [ "$response" -eq 200 ] || { echo "La requête curl a échoué avec un code de réponse différent de 200."; exit 1; }